### PR TITLE
Update Chinese Traslate

### PR DESCRIPTION
**Pull request by modcrafts**

### CODE REVIEW

**Comment by modcrafts** [comment]
Another issue 
https://www.spigotmc.org/resources/blockprot.87829/
`Languages Supported: English, German, Spanish, Turkish, Korean, Chinese (China), **Chinese (Taiwan)** `
So the more appropriate expression should be 
`Languages Supported: English, German, Spanish, Turkish, Korean, Chinese (Simplified), Chinese (Traditional)`

**Comment by spnda** [comment]
We use https://gitlocalize.com/repo/6775/ now, see #104. I'll merge this, but just so you know for the next time.

I'll also fix that on gitlocalize and spigot 👍🏻

**Comment by spnda** [comment]
> Another issue https://www.spigotmc.org/resources/blockprot.87829/ `Languages Supported: English, German, Spanish, Turkish, Korean, Chinese (China), Chinese (Taiwan)` So the more appropriate expression should be `Languages Supported: English, German, Spanish, Turkish, Korean, Chinese (Simplified), Chinese (Traditional)`

Language codes are often distinguished by a country. Traditional Chinese is more or less the same language used in many regions in Asia, but there are often differences in dialect or vocabulary. As the translation was specifically for Traditional Chinese spoken in Taiwan, I would prefer leaving it as such. I, however, don't know how it is for Simplified Chinese. Is it the same everywhere (China, Singapore, ...), or does it also have many dialects?

> The standard locale for simplified Chinese is zh_CN. The standard locale for traditional Chinese is zh_TW.

**Comment by modcrafts** [comment]
> > Another issue https://www.spigotmc.org/resources/blockprot.87829/ `Languages Supported: English, German, Spanish, Turkish, Korean, Chinese (China), Chinese (Taiwan)` So the more appropriate expression should be `Languages Supported: English, German, Spanish, Turkish, Korean, Chinese (Simplified), Chinese (Traditional)`
> 
> @modcrafts Language codes are often distinguished by a country. Traditional Chinese is more or less the same language used in many regions in Asia, but there are often differences in dialect or vocabulary. As the translation was specifically for Traditional Chinese spoken in Taiwan, I would prefer leaving it as such. I, however, don't know how it is for Simplified Chinese. Is it the same everywhere (China, Singapore, ...), or does it also have many dialects?
> 
> > The standard locale for simplified Chinese is zh_CN. The standard locale for traditional Chinese is zh_TW.

Taiwan belongs to China, if it is written this way, it may cause ambiguity to mainland Chinese players

**Comment by modcrafts** [comment]
> We use https://gitlocalize.com/repo/6775/ now, see #104. I'll merge this, but just so you know for the next time.

Submitted

**Pull request merged**
