### PR TITLE
Fix wither explosions breaking protected blocks

### PR DESCRIPTION
**Pull request by T14D3**
Prevent wither explosions from breaking locked blocks (Also bumps PlaceholderAPI version because plugin won't compile otherwise)

### CODE REVIEW

**Comment by spnda** [comment]
#320 already bumped the PAPI version.

**Comment by T14D3** [comment]
Apologies, forked before that pr was merged.

**Comment by spnda** [comment]
Isn't it weird that `EntityExplodeEvent` doesn't cover Wither explosions? That catches Creeper explosions for example... Though maybe just for being cautious this change is good to cover maybe some unknown cases.

**Comment by T14D3** [comment]
Paper has a more specific BlockDestroyEvent but if we want to maintain bukkit compat this is the only way - performance shouldn't suffer too much, have yet to see the event get called by anything but withers in my testing

**Review by spnda — APPROVED** [review]

**Pull request merged**
